### ISSUE TITLE
Problem with LSP4IJ Version

### ISSUE THREAD

**Issue by develmac** [rockofox/intellij-haskell-lsp#4] opened 2024-07-08 20:48 UTC
Since I upgraded to the version that features LSP4IJ, the plugin stopped working with the error:

"Cannot run program "haskell-language-server-wrapper": error=2, No such file or directory"

I have HLS 2.9.0.1 installed via GHCUP. 

Entering haskell-language-server-wrapper on the terminal (of macOS) does start the command. Am I missing something?

**Comment by rockofox** [comment] 2024-07-12 22:24
Thanks for the bug report! I think there's an issue that currently prevents the plugin from properly working with `haskell-language-server` installed via GHCup.
Users have already reported this in a different issue (https://github.com/rockofox/intellij-haskell-lsp/issues/2), but the issue title was unclear, so I renamed and pinned it now.
I'm working on a fix, and will reply here too once it's finished.

Duplicate of #2

**Comment by rockofox** [comment] 2024-07-12 22:25
Duplicate of #2

**Closed** 2024-07-12 22:25 UTC
